###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mailhog:
        image: mailhog/mailhog:latest
        container_name: MBT-mailhog
        restart: always
        ports:
            - 1025:1025
            - 8025:8025

    redis:
        image: redis:alpine
        container_name: MBT-redis

    mysql:
        image: mysql:8.0
        container_name: MBT-mysql
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mantisdb
            - MYSQL_USER=mantis
            - MYSQL_PASSWORD=mantis
        ports:
            - "3306:3306"

    webserver:
        image: nginx:alpine
        container_name: MBT-webserver
        working_dir: /var/www
        volumes:
            - ../code/www/MantisBugTracker:/var/www
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal

    php-fpm:
        build: phpdocker/php-fpm
        container_name: MBT-php-fpm
        working_dir: /var/www
        volumes:
            - ../code/www/MantisBugTracker:/var/www
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
